name: Test secrets
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo $DEBUG_PASSWORD >> /tmp/secrets.txt
          sleep 120
